### ISSUE TITLE
Provide a release tag for 0.3.0

### ISSUE THREAD

**Issue by Sigmanificient** [RhetTbull/strpdatetime#5]
Hi, nixpkgs contributor here. I am working on [a pr](https://github.com/NixOS/nixpkgs/pull/326978) that ports [osxphotos](https://github.com/RhetTbull/osxphotos) which depends on this package (version `0.3.0`). Due to the nature of nix, dependency are retrieved manually and I noticed that the latest GitHub release tag is `0.2.0`. I am currently fetching rev https://github.com/RhetTbull/strpdatetime/commit/121d8ef1b3d7c4dcfe012da94810fe83d869d748, but a official tag would be nice.

**Comment by RhetTbull** [comment]
Done! Created tag [v0.3.0](https://github.com/RhetTbull/strpdatetime/releases/tag/v0.3.0).

**Comment by Sigmanificient** [comment]
Thanks a lot!
